### ISSUE TITLE
Java SteamKit port

### ISSUE THREAD

**Issue by dpeger** [matty/SteamKitJ#1]
Hi, I just noticed your comment on SteamKit where you mentioned to work on a Java port of SteamKit. I'm currently trying to update the existing port (https://github.com/Top-Cat/SteamKit-Java) to work with the recent protobufs and steamd files. This includes making it more robust (i.e. include code gen projects, splitting the project and modularize it).

Are you taking SteamKit-Java as a base for your port as well? Maybe I could help out a litte. I'm pretty firm with Java but new to SteamKit and my spare time is fairly limited...

However I'm pretty exited about your port!

Best regards

**Comment by matty** [comment]
Hi, I am using parts of the code provided from that existing port like the utilities, encryption etc but mainly coding it from scratch. Implementing the use of [Netty](http://netty.io/) for the connection. I have all the protobufs up to date, I am just finishing generating the Steam Language files.

**Comment by dpeger** [comment]
I'm currently working on the steamd files as well. I'm trying to parse them with `antlr` which works fine for the enums but the classes are giving me some pain. Is there actually some kind of spec for these steamd files or is this something the SteamKit guys created from scratch?

**Comment by matty** [comment]
I believe it is something made by SteamKit from scratch.

**Comment by dpeger** [comment]
Are you hand coding your parser/codegen stuff? Especially the `header.steamd` `MsgHdrProtoBuf` is kind of confusing me.

**Comment by matty** [comment]
Have a look at the files i've generated so far:

[steam.zip](https://github.com/matty/SteamKitJ/files/213793/steam.zip)

The parser is already written in SteamKit called "SteamLanguageParser" project. I have generated the protobufs using Google Protobuf (protoc binary) and then the language files using SteamKits C# project. (will convert this to Java when I have time).

**Comment by matty** [comment]
Let me tidy what I have so far and i'll commit to the repository asap.

**Comment by dpeger** [comment]
Thanks. This looks pretty similar to the files in SteamKit-Java.

I'm working on MacOS that is the existing parser is not of much use to me. For that reason I'm creating it from scratch. This is kind of a training exercise though...

**Comment by matty** [comment]
I use Mac too but I used a VM to get it working.

**Comment by matty** [comment]
Feel free to join me on Gitter at https://gitter.im/matty/SteamKitJ
